dhis2/scheduler-app

- .travis.yml
- deploy/settings.xml
All builds of master will be auto-deployed. Stable branches will only deploy when tagged.
> Travis automation

- .eslintrc
- app/src/components/jobContent/ActionButtons.jsx
- app/src/components/jobContent/AddJob.jsx
- app/src/components/jobContent/Content.jsx
- app/src/components/jobContent/EditJob.jsx
- app/src/reducers/jobsReducer.js
- app/src/reducers/pendingReducer.js
- app/src/store.js
- Create reducer for handling pending states
- Apply this reducer to adding, saving and deleting jobs
- Disable buttons and add a progress-icon when actions are pending
- Refactor ActionButtons props
> Improve user feedback when updating and deleting jobs

- src/utils/apiTranslations.js
Fixes https://jira.dhis2.org/browse/DHIS2-7234
> fix: add translations for new job types

- package.json
- src/components/App.jsx
- src/index.js
- webpack.dev.js
- yarn.lock
Since @ismay is working on a larger refactor of this application, this relies on the existing hacks to make it work.
> fix: update headerbar to latest and greatest

- src/api/api.js
- src/components/jobContent/Content.jsx
- src/components/jobContent/EditJob.jsx
- src/components/jobContent/Schedule.jsx
- src/components/jobOverview/Entry.jsx
https://jira.dhis2.org/browse/DHIS2-8161
Removed the continuous execution toggle from the UI. Continuous execution is also no longer present in the payload for updating and creating jobs.
Note: Tests fail locally, but they fail for me locally on master as well. Tests aren't run on CI, so I'm not sure when this started failing. Since it's failing on master as well I'm not considering it a regression (though it is something we should fix).
> refactor: remove continuous execution toggle

- i18n/en.pot
- src/actions/epics.js
- src/api/api.js
- src/components/App.jsx
- src/components/jobContent/AddJob.jsx
- src/components/jobContent/Content.jsx
- src/components/jobContent/EditJob.jsx
- src/components/jobContent/JobType.jsx
- src/components/jobContent/Schedule.jsx
- src/components/jobOverview/Entry.jsx
- src/constants/cronExpressions.js
- src/constants/schedulingTypes.js
- src/reducers/jobsReducer.js
- src/utils/apiTranslations.js
- src/utils/configI18n.js
- src/utils/validDelay.js
Backport of https://github.com/dhis2/scheduler-app/pull/46
> fix: revert to old translation strategy

- package.json
- src/components/AuthWall/AuthWall.js
- src/components/Buttons/CronPresetButton.js
- src/components/Buttons/DeleteJobButton.js
- src/components/Buttons/DiscardFormButton.js
- src/components/Cron/HumanReadableCron.js
- src/components/FormFields/LabeledOptionsField.js
- src/components/FormFields/ParameterFields.js
- src/components/FormFields/ScheduleField.js
- src/components/FormFields/UnlabeledOptionsField.js
- src/components/Forms/JobForm.js
- src/components/Forms/JobFormContainer.js
- src/components/Modal/CronPresetModal.js
- src/components/Modal/DeleteJobModal.js
- src/components/Modal/DiscardFormModal.js
- src/components/Modal/RunJobModal.js
- src/components/PageWrapper/PageWrapper.js
- src/components/Switches/ToggleJobSwitch.js
- src/pages/JobList/DeleteJobMenuItem.js
- src/pages/JobList/EditJobMenuItem.js
- src/pages/JobList/JobList.js
- src/pages/JobList/JobListActions.js
- src/pages/JobList/JobListTable.js
- src/pages/JobList/JobListTableItem.js
- src/pages/JobList/JobNextRun.js
- src/pages/JobList/JobSchedule.js
- src/pages/JobList/JobStatus.js
- src/pages/JobList/RunJobMenuItem.js
- yarn.lock
Updates to the latest release of our prop-types lib.
> fix(prop-types): update prop types

- package.json
- src/.eslintrc.js
- yarn.lock
Update cli-style to latest version. Could upgrade to https://github.com/dhis2/cli-style/pull/250 as well (and update the local rules).
> chore: update cli-style

- .github/dependabot.yml
- .github/semantic.yml
- .github/workflows/comment-and-close.yml
- .github/workflows/dhis2-verify-app.yml
- .travis.yml
- package.json
The travis CI integrations were disabled for all our repos, this adds the GH actions to replace them.
> ci(github): add github workflow files

- src/pages/JobEdit/JobEdit.js
https://jira.dhis2.org/browse/DHIS2-10270
Small fix, ensures info link opens in new tab, like it does in the rest of the app.
> fix(infolink): ensure infolink opens in new window

- package.json
- src/.eslintrc.js
- yarn.lock
Added a linter that checks that children aren't just string literals.
> test(translations): ensure all text is translated

- i18n/en.pot
- src/components/AuthWall/AuthWall.js
- src/components/AuthWall/AuthWall.test.js
- src/pages/JobList/JobListContainer.js
- src/pages/JobList/JobListContainer.test.js
https://jira.dhis2.org/browse/DHIS2-10275
> fix(loading): render spinners without text when loading

- src/pages/JobList/JobList.js
- src/pages/JobList/JobList.module.css
https://jira.dhis2.org/browse/DHIS2-10277
> feat(info): add info link for job listing

- i18n/en.pot
- package.json
- src/components/FormFields/ParameterFields.js
- src/components/FormFields/ParameterFields.test.js
- src/components/FormFields/SkipTableTypesField.js
- src/components/FormFields/SkipTableTypesField.test.js
- src/services/server-translations/analyticsTableTypes.js
- src/services/server-translations/index.js
https://jira.dhis2.org/browse/DHIS2-10305
Eventually I think we should break up the ParameterFields component into smaller ones. Plus I'd like to change the tests as well, there's several things there I think could be improved.
> fix: translate server strings

- i18n/en.pot
- src/components/AuthWall/AuthWall.js
- src/components/AuthWall/AuthWall.module.css
- src/components/AuthWall/AuthWall.test.js
- src/components/Routes/Routes.js
- src/pages/NotAuthorized/NotAuthorized.js
- src/pages/NotAuthorized/NotAuthorized.test.js
- src/pages/NotAuthorized/index.js
Modifying the unauthorized state to fit Joe's recommendations.
https://jira.dhis2.org/browse/DHIS2-10276
> fix(unauthorized): show noticebox for unauthorized users

- src/components/Forms/JobAddForm.js
- src/components/Forms/JobEditForm.js
Cleaning up the subscriber with useeffect. And added explanatory comments.
> fix(useeffect): cleanup subscriber

- cypress/integration/add-route/back-to-all-jobs.feature
- cypress/integration/add-route/create-parameter-jobs.feature
- cypress/integration/add-route/create-parameterless-jobs.feature
- cypress/integration/add-route/cron-presets.feature
- cypress/integration/add-route/info-link.feature
- cypress/integration/edit-route/back-to-all-jobs.feature
- cypress/integration/edit-route/cron-presets.feature
- cypress/integration/edit-route/delete-button.feature
- cypress/integration/edit-route/display-jobs.feature
- cypress/integration/edit-route/edit-parameter-jobs.feature
- cypress/integration/edit-route/edit-parameterless-jobs.feature
- cypress/integration/edit-route/info-link.feature
- cypress/integration/list-route/filter-jobs.feature
- cypress/integration/list-route/include-system-jobs.feature
- cypress/integration/list-route/info-link.feature
- cypress/integration/list-route/job-toggle.feature
- cypress/integration/list-route/list-user-jobs.feature
- cypress/integration/list-route/new-job.feature
- cypress/integration/list-route/system-job-actions.feature
- cypress/integration/list-route/user-job-actions.feature
https://jira.dhis2.org/browse/DHIS2-10472
> test(cypress): add feature files

- cypress/integration/list-route/job-toggle.feature
- cypress/integration/list-route/system-job-actions.feature
- cypress/integration/view-route/back-to-all-jobs.feature
- cypress/integration/view-route/display-jobs.feature
- cypress/integration/view-route/info-link.feature
- i18n/en.pot
- src/components/JobTable/Actions.js
- src/components/JobTable/JobTableRow.js
- src/components/JobTable/ViewJobAction.js
- src/components/JobTable/ViewJobAction.test.js
- src/components/Routes/Routes.js
- src/components/Switches/ToggleJobSwitch.js
- src/components/Switches/ToggleJobSwitch.test.js
- src/pages/JobView/JobView.js
- src/pages/JobView/JobView.module.css
- src/pages/JobView/JobView.test.js
- src/pages/JobView/index.js
https://jira.dhis2.org/browse/DHIS2-10504
> fix(system-jobs): enforce system job permissions

- .github/workflows/dhis2-verify-app.yml
This updates the workflow to the latest version.
> ci(workflow): update dhis2 workflow

- i18n/en.pot
- src/services/server-translations/jobTypesMap.js
This adds a new jobType that was added on the backend.
> fix(jobtype): add new disable inactive users job type 

- src/components/JobTable/RunJobAction.js
- src/components/JobTable/RunJobAction.test.js
https://jira.dhis2.org/browse/DHIS2-10606
> fix(jobtable): disable manual job run if job itself is disabled

- src/pages/JobAdd/JobAdd.js
- src/pages/JobEdit/JobEdit.js
- src/pages/JobList/JobList.js
- src/pages/JobView/JobView.js
Updated the documentation links. 
Fixes: https://jira.dhis2.org/browse/DHIS2-10463
> fix(docs-link): fix documentation link

- src/components/App/App.js
https://jira.dhis2.org/browse/DHIS2-10635
> fix(translations): import locales to enable translations

- .tx/config
https://jira.dhis2.org/browse/DHIS2-10635
> fix(translations): fix transifex mapping

- .github/workflows/dhis2-verify-app.yml
- package.json
- src/.eslintrc.js
- src/components/App/App.js
- yarn.lock
This fixes a couple of configuration mistakes I noticed whilst working on the cli-style eslint PRs.
> fix(linting): import linting fixes from cli-style

- src/api/api.js
Fixes https://jira.dhis2.org/browse/DHIS2-10754
See slack conversation here: https://dhis2.slack.com/archives/C1XNHEY0L/p1616601672007100
> fix(notifications): fix empty errorreports triggering an error message

- .github/workflows/dhis2-verify-app.yml
This imports the latest changes from https://github.com/dhis2/workflows. After this I'll sync back any changes we made to the e2e config for cypress to the workflows repo (see follow up here: https://github.com/dhis2/scheduler-app/pull/206).
> ci(verify): import changes from workflows repo

- .github/workflows/dhis2-verify-app.yml
Imported the latest changes from the workflows repo.
> ci(actions): update workflow to latest

- package.json
- yarn.lock
https://jira.dhis2.org/browse/LIBS-200. Updating to the new app-runtime release.
Follow up:
> chore(deps): update app-runtime

- src/services/validators/validate-cron.js
- src/services/validators/validate-cron.test.js
Closes DHIS2-14016 ([link](https://dhis2.atlassian.net/browse/DHIS2-14016))
> fix(validate cron): allow ranges in fraction numerators

- src/components/FormFields/QueueOrderField/CustomOption.module.css
Fixes: https://dhis2.atlassian.net/browse/DHIS2-16411
> fix: add cursor pointer to custom transfer options

- cypress/integration/list/actions-queue.feature
- cypress/integration/list/actions-queue/index.js
- i18n/en.pot
- src/components/JobTable/QueueActions.js
- src/components/JobTable/QueueActions.test.js
- src/components/JobTable/QueueTableRow.js
- src/components/JobTable/RunQueueAction.js
- src/components/JobTable/RunQueueAction.test.js
- src/components/Modal/RunJobModal.js
Adds the run manually menu item to the actions menu:
See: https://dhis2.atlassian.net/browse/DHIS2-16406
> feat: add run queue menu item
