app/src/api/__tests__/interface.spec.js
app/src/components/MessagePanel.jsx
app/src/components/jobContent/ActionButtons.jsx
app/src/reducers/__tests__/jobsReducer.spec.js
app/src/reducers/__tests__/messageReducer.spec.js
app/src/reducers/jobsReducer.js
app/src/reducers/messageReducer.js
package.json

* Added tests for job- and message reducers
* Added moduleNameMapper for jest in config
* Added a mock for i18next, might want to move this out of messageReducer test later
* Changed message reducer to use an ID counter instead of timestamps for triggering rerendering
- Timestamps weren't needed

Add reducer tests, fix minor reducer bugs

---

src/utils/apiTranslations.js

This adds two new (english) translations for the job types. Do not merge unless we have an OK from QA!

fix: add translations for new job types

---

cypress/integration/Overview_cron_next_execution.feature
cypress/integration/Overview_show_delay_time.feature
cypress/integration/Scheduling_types_in_form.feature

Relates to DHIS2-8164
This adds feature files to describe the behavior for delay schedule-types and the introduced differences between delay and cron scheduling-types.

docs(scheduling type): describe behavior for delay & differences to cron

---

i18n/en.pot
src/constants/cronExpressions.js

https://jira.dhis2.org/browse/DHIS2-8301
I was curious what was going wrong here, so I quickly created this. Tbh. I'm not sure how this worked in the past. There haven't been any translations for these labels for what I could find, but I suspect I'm overlooking sth. If we can find the core issue that'd be best, otherwise this at least patches the reported bug.
(I don't see why we would use SCREAMING_SNAKE_CASE or macro case for the cron preset labels. It's not referenced anywhere else, so might as well make that human friendly)
Might be that we have to update the translations in transifex btw, not here, I'm not sure atm. (edit: we don't, transifex is not enabled yet for this app).

fix: use human readable cron label strings

---

src/pages/JobList/JobListTableItem.js
src/pages/JobList/JobListTableItem.test.js
src/pages/JobList/JobNextRun.js
src/pages/JobList/JobNextRun.test.js
src/pages/JobList/__snapshots__/JobListTableItem.test.js.snap
src/pages/JobList/__snapshots__/JobNextRun.test.js.snap

Small inbetween fix following up on a todo point from #38. I thought that there was a bug in the jobConfigurations endpoint, as it seemed to be returning timestamps in the past.
But after talking to Morten about it I understand that this endpoint can be assumed to return UTC time (see slack [here](https://dhis2.slack.com/archives/C1XNHEY0L/p1585128053002800)). So I'm now parsing it as UTC and have abstracted it to a separate component and added some tests.

refactor: fix next run time display

---

src/components/FormFields/DelayField.js
src/components/FormFields/JobTypeField.js
src/components/FormFields/ParameterFields.js
src/components/FormFields/ScheduleField.js
src/components/FormFields/index.js
src/components/Forms/JobForm.js
src/hooks/job-types/use-get-job-types.js
src/pages/JobList/JobListTable.test.js
src/pages/JobList/JobListTableItem.js
src/pages/JobList/JobListTableItem.test.js
src/pages/JobList/JobNextRun.js
src/pages/JobList/JobSchedule.js
src/pages/JobList/__snapshots__/JobListTable.test.js.snap
src/pages/JobList/__snapshots__/JobListTableItem.test.js.snap

This pulls in the latest changes from master, specifically:
* https://github.com/dhis2/scheduler-app/commit/bb3a908c2f7bc75a9587376808b7fba236129ddc
* https://github.com/dhis2/scheduler-app/commit/e14ccd8541cbee6769dbd645cd9b9a49fcfac9e5
There were changes to add a new scheduling type; `FIXED_DELAY`. The design for the refactor was made before these job types were introduced, so until we have a new design, this will just allow the app to work with the new job types in the same manner as master.
1. Fixed delay jobs do not get a nextExecutionTime at the moment. We could calculate that client side, but since the scheduling logic should already be present on the backend, it's probably best to retrieve it from there to prevent divergence. Once addressed on the backend the app will display the …

fix: import upstream scheduling type changes

---

.eslintignore
src/.eslintrc.js
src/components/Buttons/index.js
src/components/FormFields/DelayField.js
src/components/NoticeBox/NoticeBoxIcon.test.js
src/components/NoticeBox/NoticeBoxMessage.test.js
src/components/NoticeBox/NoticeBoxTitle.test.js
src/hooks/job-types/index.js
src/hooks/jobs/index.js
src/hooks/me/index.js
src/hooks/parameter-options/index.js
src/hooks/user-settings/index.js
src/services/history/index.js

Enabling some useful rules, see: https://github.com/benmosher/eslint-plugin-import. This adds checks for common import mistakes/anti-patterns (like no cyclical dependencies, no unused modules, etc.). Other than that it enables some style rules that allow us to have to think less about how we're writing our imports, since `eslint --fix` will keep it consistent for us.
* The `import/no-internal-modules` rule enforces the existing repo structure. It ensures that the index.js of every folder in `components`, `hooks`, `pages` and `services` is always the external boundary. Which will hopefully make the interaction between the different parts of the app easier to reason about, we'll see how it works out in practice though.
* I've kept the plugin's bundled warnings and errors. We're setting most …

chore: update eslint config

---

i18n/en.pot
src/actions/epics.js
src/api/api.js
src/components/App.jsx
src/components/jobContent/AddJob.jsx
src/components/jobContent/Content.jsx
src/components/jobContent/EditJob.jsx
src/components/jobContent/JobType.jsx
src/components/jobContent/Schedule.jsx
src/components/jobOverview/Entry.jsx
src/constants/cronExpressions.js
src/constants/schedulingTypes.js
src/reducers/jobsReducer.js
src/utils/apiTranslations.js
src/utils/configI18n.js
src/utils/validDelay.js

The translations in this app were broken in a couple of places (and I noticed my fix from earlier was incomplete). I tracked it down to [this line](https://github.com/dhis2/scheduler-app/blob/ab3cd673111847520d5464072cb04dafda3053d8/src/utils/configI18n.js#L19), where the namespace used is no longer correct (but `default` works as expected).
See [this issue](https://github.com/dhis2/app-platform/issues/369) for more info on why using the `default` namespace fixes the translations. This fix means that the translations in [apiTranslations.js](https://github.com/dhis2/scheduler-app/blob/ab3cd673111847520d5464072cb04dafda3053d8/src/utils/apiTranslations.js) are now picked up again.
Todo:
Ref: https://jira.dhis2.org/browse/DHIS2-8709
Docs: https://www.i18next.com/principles/namespaces
As for …

fix: revert to old translation strategy

---

.travis.yml

Fixes the buid failure on the refactor-scheduler branch. For some reason upgrades to our libs sometimes require you to `rm -rf node_modules && yarn`. This is a temporary fix to address that, though in the long run we should definitely make sure that our libs don't require this, because it's affecting the reliability/reproducibility of our dependency installations.

ci(travis): fix build error

---

src/hooks/jobs/use-update-job.js

In going through the [docs](https://docs.dhis2.org/master/en/developer/html/webapi_scheduling.html) for the Jira epic I'm currently updating, I noticed that the docs mention that an update of a job should be possible with a PUT.
I know that in the past I encountered a bug there, and updating only worked with PATCH, but now that I've tested again it seems to be working just fine. Since this is what the docs recommend, I've changed this hook to use the recommended approach.

fix(update-job-hook): use PUT for job configuration update

---

src/api/api.js

With a successful job we're getting an empty array, which caused the line I've changed to throw. By checking whether there are actually any errors it now only throws if we're getting errorreports.
Closes #56
Note: don't merge until we've got approval from the release board.

fix: job run throwing error for successful job

---

src/api/api.js

Closes #56
See: https://github.com/dhis2/scheduler-app/pull/57

fix: only throw job run error if there are error reports

---

i18n/en.pot
src/components/FormFields/ParameterFields.js

I accidentally took the header verbatim from the design, but `Monitoring` shouldn't be part of the header, so I simplified it to just `Parameters`, so that it applies everywhere.

fix(job-form): fix parameter header

---

i18n/en.pot
src/components/JobTable/Actions.js
src/components/JobTable/Actions.test.js
src/components/JobTable/DeleteJobAction.js
src/components/JobTable/DeleteJobAction.test.js
src/components/JobTable/EditJobAction.js
src/components/JobTable/EditJobAction.test.js
src/components/JobTable/JobTable.js
src/components/JobTable/JobTable.test.js
src/components/JobTable/JobTableRow.js
src/components/JobTable/JobTableRow.test.js
src/components/JobTable/NextRun.js
src/components/JobTable/NextRun.test.js
src/components/JobTable/RunJobAction.js
src/components/JobTable/RunJobAction.test.js
src/components/JobTable/Schedule.js
src/components/JobTable/Schedule.test.js
src/components/JobTable/Status.js
src/components/JobTable/Status.test.js
src/components/JobTable/index.js
src/pages/JobList/JobList.js
src/pages/JobList/JobList.test.js

I've extracted the job table from the job list route. All the job table components cluttered up the job list route and made it harder to work on. Since the job table is a piece of functionality that seems quite self contained, I've moved it to its own folder.

refactor(jobtable): extract job table from joblist route for clarity

---

src/components/Forms/JobEditFormContainer.js
src/components/Forms/JobEditFormContainer.test.js

I missed a query when moving everything to the store. This takes care of the last remaining dataquery.

fix(editform): replace query with store

---

src/pages/JobView/JobView.js

Lesson learned. What went wrong is that I trusted the GH ui too much. It said I could merge without conflicts, but actually, 80 and 81 were not rebased on master. So even though we could merge without conflicts, it did create a part of the app that relied on code that was removed in 80 & 81. So always rebase on master, or run tests and linting on the resulting code after the merge as well.

fix(view-route): use hooks instead of selectors

---

.tx/config

Restores the transifex config from this commit: https://github.com/dhis2/scheduler-app/commit/eb6b1a496024189f0419af77aa41c0da54d3c72b

chore(translations): restore transifex config

---

package.json
src/utils/configI18n.js
yarn.lock

https://jira.dhis2.org/browse/DHIS2-10635
Setting the namespace to default for v33, v34 and v35. It was causing issues on some branches. This way it's consistent everywhere.

fix(translations): use default namespace for translations

---

.github/workflows/dhis2-verify-app.yml
package.json
yarn.lock

Example for how to align the CI with the new alpha version of `d2-utils-cypress`.

chore: update cypress (viva patch)

---

i18n/en.pot
src/components/Modal/RunJobModal.js
src/components/Modal/RunJobModal.test.js

Closes https://jira.dhis2.org/browse/DHIS2-12156
[The HTTP method for the `jobConfigurations/:id/execute` endpoint has switched from `GET` to `POST`](https://github.com/dhis2/dhis2-core/pull/9252).
The `RunJobModal` component has been updated to use `POST`.

fix: switch to POST for executing jobs

---

src/components/FormFields/JobTypeField.js

The JobType `TRACKER_SEARCH_OPTIMIZATION` is not implemented yet, and thus shows as a blank field in the input selection. The API for implementing this jobType does not seem complete: https://jira.dhis2.org/browse/DHIS2-12048 . This prevents future new non-implemented jobTypes from showing as blank fields in the selector. 
Also added sorting of the Job-types. A bit debatable if this should be added here, but I think it's a good quality of life improvement.

fix(job-type-field): filter non-implemented jobTypes

---

.github/workflows/dhis2-netlify-deploy-pr.yml
.github/workflows/dhis2-netlify-deploy-production.yml
.github/workflows/dhis2-verify-app.yml

As discussed, node 12 is EOL. There are some deprecations in node 18 that we need to address, so node 16 is the most modern version we can update to at the moment.

fix(node): update node 12 to node 16

---

.github/workflows/dhis2-verify-app.yml

E2e tests were accidentally disabled here it seems: https://github.com/dhis2/scheduler-app/commit/934d73502fe9707fb12e31990ec548482d74fd29#diff-1d835fdd19fc1d6a0129eb898bf4593f444624610ad0ee1311c1a7ae906f70b7R86. This could go unnoticed because these checks aren't required.
This reenables the e2e tests. We should also make them required in the repo settings.

ci(e2e): reenable e2e tests

---

src/components/Store/hooks.js

Fixes https://dhis2.atlassian.net/browse/DHIS2-15095. Note that this just fixes the crash. Parameters of the `java.util.List` type usually need to fetch their options. We need a `relativeApiEndpoint` for this parameter type if that's the case, and add the query manually as it needs to be static.

fix(parameter-options): return empty array if parameter options do not exist

---

d2.config.js
package.json

This sets the min version for the changes in the PR. 2.40 is the first version that includes the endpoints used in the PR.

chore: specify 2.40 as minimum version

---

d2.config.js

Upcoming changes require 2.40 as the minimum version. Current app will be kept around for versions below 2.40.

chore: specify 2.39 as maximum version

---

.github/workflows/dhis2-netlify-deploy-pr.yml
.github/workflows/dhis2-netlify-deploy-production.yml
.github/workflows/dhis2-verify-app.yml
.github/workflows/dhis2-verify-commits.yml

https://github.com/c-hive/gha-yarn-cache is deprecated. It has been integrated in https://github.com/actions/setup-node, see: https://github.com/actions/setup-node#caching-global-packages-data. This applies the recommended migration.

ci(cache): update workflows to recommended caching approach

---

src/components/Forms/JobAddFormContainer.js
src/components/Forms/JobEditFormContainer.js
src/components/Forms/SequenceAddFormContainer.js
src/hooks/job-queues/use-submit-job-queue.js
src/hooks/job-queues/use-submit-job-queue.test.js
src/hooks/jobs/use-submit-job.js
src/hooks/jobs/use-submit-job.test.js
src/hooks/jobs/use-update-job.js
src/hooks/jobs/use-update-job.test.js

Removes the hardcoded redirect on success and allows us to get rid of some of the mocking.
https://dhis2.atlassian.net/browse/LIBS-515

refactor(submit-hooks): accept onSuccess callback for submission hooks

---

src/components/JobTable/Actions.js
yarn.lock

https://dhis2.atlassian.net/browse/TECH-1300
Before this fix we used to check whether a job was configurable and show a manual run option only if it was. Currently we don't want to block manual runs for system jobs anymore, so I've removed the condition. Manual run will be available for all types of jobs.
The dialog for system jobs before this fix:
And after this fix:
Triggering a manual run of a system job will send this kind of POST:

fix(system-jobs): always allow running jobs manually

---

.github/workflows/dhis2-verify-app.yml

Since we're running out of credits often for cypress I've disabled recording and parallelization. Not as fast, but it won't cost us any cypress credits and it'll at least run again.

ci(cypress): stop using cypress dashboard

---

src/components/JobTable/NextRun.js
src/components/JobTable/NextRun.test.js

https://dhis2.atlassian.net/browse/DHIS2-14787
https://dhis2.atlassian.net/browse/DHIS2-15764 (partially)
We used to show `Not scheduled` under the `Next run` column for jobs that had their `nextExecutionTime` in the past, like so:
The intention was to indicate to users that the next run hadn't been planned yet, because the backend was working on executing it at that point, and would only schedule a new job after. That was confusing users a little, because we still showed `scheduled` as the job status.
So to indicate that the backend is currently working on trying to execute the job, this changes that to show `Now` instead:
Since we don't have a lot of space to tell the user the whole story, "Now" seems the most correct and easy to understand.

fix: update label to indicate job is attempting to run now

---

src/components/Modal/CronPresetModal.js

Some of our cron labels were incorrect: https://dhis2.atlassian.net/browse/DHIS2-12570. I've fixed the cron expressions to actually be the schedules that the labels are describing.
As a follow up issue we could look into creating a better selection of presets. I'll create a Jira issue for that.

fix: align cron expressions with labels

---

cypress/integration/add-job/back-to-all-jobs/index.js
cypress/integration/add-queue/back-to-all-jobs/index.js
cypress/integration/edit-job/back-to-all-jobs/index.js
cypress/integration/edit-queue/back-to-all-jobs/index.js
i18n/en.pot
src/components/Modal/DiscardFormModal.js

This improves the discard form dialog text. The text was a little confusing, and has been updated to provide a little more context and clarity (hopefully).
See the linked issue for more details: https://dhis2.atlassian.net/browse/DHIS2-16413

fix: improve text for discard form modal

---

cypress/integration/add-job/create-parameterless-jobs/index.js
cypress/integration/edit-job/edit-parameterless-jobs/index.js
src/components/FormFields/Custom/DataIntegrityReportTypeField.js

Changes the defaultValue of `Report` type for `Data integrity` job to be `summary` instead of `report`.
Report is a legacy type, and isn't really useful at all when scheduling. So we may remove this completely.
Also fixes a bug where I'd used `initialValue` for the field instead of `defaultValue`. This is the wrong prop to use it in this case. Because `initialValue` would override the `initialValues` on the form, and meant this field would always be set to `report` when you edited a job. Which is actually a quite bad bug.
I just discovered this bug when trying to schedule summary jobs in conjunction with the new Data Integrity UI in `Data Administration` app.
However, this bug does not seem to happen in 2.39 and 2.38. I am not sure what introduced it, but it seems like it's currectly in …

fix(data-integrity): change default report type to summary

---

i18n/en.pot
src/components/FormFields/Custom/DataIntegrityChecksField.js
src/components/FormFields/Custom/DataIntegrityChecksField.module.css

Adds an indicator to checks that have `isSlow: true`. The new UI in `Data Administration` separates these checks completely, because the user should be cautious when running these checks. So I think it's quite important to distinguish those here as well.

fix(data-integrity): add indicator for slow checks

---

i18n/en.pot
src/components/FormFields/QueueTransfer.js
src/components/JobDetails/JobDetails.js
src/pages/JobEdit/JobEdit.js
src/pages/JobView/JobView.js

https://dhis2.atlassian.net/browse/DHIS2-17022
See https://final-form.org/docs/react-final-form/api/Field for the fix I used in the last commit:
> Note: To use an array for the values (with another field type, like a tags-input component), you can do value={[...props.input.value]} to avoid "Invalid prop type of 'string' warning"
There are other ways to fix it, like defaultValues or initialValues. But initialValues on a field would override the ones we set on the form, which would prevent us seeding the form with data when editing a queue. And using a defaultValue would mean the form is dirty as soon as it's initialized, which is confusing for users. The fix suggested above is not ideal, but the least bad in my opinion.

fix: proptype errors

---

src/services/validators/validate-cron.js
src/services/validators/validate-cron.test.js

See https://dhis2.atlassian.net/browse/DHIS2-18859
This fixes an issue where the parsing of cron expressions would compare two strings, e.g. `'4'`, and `'23'` and '4' < '23' evaluates to `false`.

fix: cron parsing number range [DHIS2-18859]

---

src/services/validators/validate-cron.js
src/services/validators/validate-cron.test.js

This PR fixes a bug that Lina noticed while testing https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-18859
The original ticket was to allow ranges like `4-23` whereas previously the validation check was making you enter `04-23`
When Lina was testing she was typing and had a point where she had something like `0 0 -23 * * *`. This was not rejected by our validator, which in turn led the app to crash because it is an invalid cron expression that was being passed to a cron expression interpreter (to output it in natural language).
Anyway, this bug is closely related to the ticket I was working on (it's another bug related to number ranges), so I think it makes sense to just put the fix on the original ticket.
I also considered adding a catch for the cron interpreter, …

fix: check if start of range is valid

---

i18n/en.pot
src/services/server-translations/jobTypesMap.js

See https://dhis2.atlassian.net/browse/DHIS2-12051
The backend PR changes the name of the job type from `TRACKER_SEARCH_OPTIMIZATION` to `TRACKER_TRIGRAM_INDEX_MAINTENANCE`. This means we need to add `TRACKER_TRIGRAM_INDEX_MAINTENANCE` into the list of know job types.
In order to be backwards compatible and non-feature toggled, it's easiest to just add the new name rather than to replace it.

fix: add new jobType name [DHIS2-12051]
